# Generated by Django 4.2.6 on 2023-11-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Diabet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Pregnancies", models.IntegerField()),
                ("Glucose", models.IntegerField()),
                ("BloodPressure", models.IntegerField()),
                ("SkinThickness", models.IntegerField()),
                ("Insulin", models.IntegerField()),
                ("BMI", models.FloatField()),
                ("DiabetesPedigreeFunction", models.FloatField()),
                ("Age", models.IntegerField()),
                ("Outcome", models.BooleanField()),
            ],
        ),
    ]
